"""Generate a HARD retrieval benchmark for the Swarna Andhra bot.

Why this exists
---------------
The existing gold benchmark reports 100% retrieval (195/195), so it cannot detect
whether a corpus or retrieval change helps or hurts. That number is also inflated by
construction: every numeric gold prompt names a district, `app.detect_district` fires,
and `app.retrieve` force-injects that district's snapshot at score 1.0 -- so the target
figure is present in the context almost tautologically. It measures the district-forcing
rule, not the embeddings.

This benchmark measures something the current system can actually fail: given a question,
does the retriever return THE SPECIFIC SOURCE CHUNK that answers it?

Ground truth is a (source, page) pair, not a substring of the answer. Questions are
generated by Haiku from a known chunk and are explicitly steered away from the chunk's own
vocabulary, so passing requires semantic matching rather than keyword overlap.

Output: hard_retrieval.jsonl -- one JSON object per line:
  {id, stratum, prompt, gold_source, gold_page, gold_folder, overlap, chunk_preview}

Usage:  venv/bin/python gen_hard_retrieval.py [n_per_stratum_override]
"""
import json
import pickle
import random
import re
import subprocess
import sys
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor

CHUNKS_PKL = "embed_chunks.pkl"
OUT = "hard_retrieval.jsonl"
GEN_MODEL = "haiku"
WORKERS = 6
random.seed(17)

# Target counts per stratum. Deliberately over-weights methodology: it is only 253 of
# 59,388 chunks (0.4%) yet is a core use case, so it must win top-k against ~57.7k
# vision chunks. That contest is invisible in the current gold set.
STRATA = {
    "method_paraphrase": 40,
    "vision_specific":   45,
    "numeric_table":     40,
    "ambiguous_mandal":  20,
    "district_profile":  20,
    "training_case":     15,
}

STOP = set("""a an the and or of in on for to is are was were be been being at by with from
as that this these those it its their his her they we you i not no but if then than so such
what which who whom how when where why does do did has have had will would can could should
about into over under between across per each any all more most other some only own same""".split())


def words(s):
    return set(w for w in re.findall(r"[a-z]+", s.lower()) if len(w) > 3 and w not in STOP)


def overlap_ratio(question, chunk_text):
    """Fraction of the question's content words that appear verbatim in the chunk.

    High overlap means the question can be answered by keyword matching, which does not
    test the embeddings. Used to filter generated questions.
    """
    qw = words(question)
    if not qw:
        return 1.0
    return len(qw & words(chunk_text)) / len(qw)


def digit_density(text):
    return len(re.findall(r"\d", text)) / max(len(text), 1)


# ---------------------------------------------------------------- chunk selection

def pick_pools(chunks):
    """Bucket chunk indices into the strata we want to sample from."""
    pools = defaultdict(list)

    # mandal filenames that occur under more than one constituency -- retrieving the
    # right one requires disambiguating on district/constituency, not just the name.
    mandal_paths = defaultdict(set)
    for c in chunks:
        p = c["source"].split("/")
        if len(p) >= 5 and p[1] == "mandal":
            mandal_paths[p[4]].add((p[2], p[3]))
    ambiguous = {k for k, v in mandal_paths.items() if len(v) > 1}

    for i, c in enumerate(chunks):
        folder, src, text = c.get("folder"), c["source"], c["text"]
        if len(text) < 400:            # too thin to support a specific question
            continue
        parts = src.split("/")

        if folder == "methodology":
            pools["method_paraphrase"].append(i)
        elif folder == "district_data":
            pools["district_profile"].append(i)
        elif folder in ("training", "case_studies"):
            pools["training_case"].append(i)
        elif folder == "vision_documents":
            if len(parts) >= 5 and parts[4] in ambiguous:
                pools["ambiguous_mandal"].append(i)
            elif digit_density(text) > 0.06:
                pools["numeric_table"].append(i)
            else:
                pools["vision_specific"].append(i)
    return pools


# ---------------------------------------------------------------- question generation

PROMPT_TMPL = """You are building a retrieval test set for a government economics assistant \
used by Andhra Pradesh officials.

Below is ONE passage from an official document. Write ONE question that a government officer \
would plausibly ask, which this passage answers.

Hard requirements:
- The question must be answerable from this passage specifically, not from general knowledge.
- REPHRASE. Do not reuse distinctive nouns, phrases or headings from the passage. Use synonyms \
and everyday officer phrasing instead. The test is whether a semantic search engine can find \
this passage WITHOUT keyword overlap.
- {scope}
- One sentence. No preamble, no quotes, no explanation.

DOCUMENT PATH: {source}
PASSAGE:
{text}

Output ONLY the question."""

SCOPE = {
    "method_paraphrase":
        "Ask about the concept, definition or procedure. Do NOT name the document.",
    "vision_specific":
        "Name the place (mandal/constituency/district) so the question is unambiguous, "
        "but rephrase everything else.",
    "numeric_table":
        "Ask for a specific figure, target or rate that appears in the passage. "
        "Name the place, but describe the indicator in your own words.",
    "ambiguous_mandal":
        "You MUST name both the mandal AND its district or constituency, because this "
        "mandal name occurs in more than one place in Andhra Pradesh.",
    "district_profile":
        "Name the district. Ask about its economic structure or sector mix.",
    "training_case":
        "Ask about the case study's lesson, sector or replicable mechanism.",
}


def gen_one(args):
    idx, chunk, stratum = args
    text = chunk["text"][:2500]
    prompt = PROMPT_TMPL.format(scope=SCOPE[stratum], source=chunk["source"], text=text)
    try:
        r = subprocess.run(["claude", "-p", "--model", GEN_MODEL], input=prompt,
                           capture_output=True, text=True, timeout=120)
        q = (r.stdout or "").strip().strip('"').split("\n")[0].strip()
    except Exception as e:
        print(f"  ! gen failed for {chunk['source']}: {e}")
        return None
    if not q or len(q) < 15 or not q.endswith("?"):
        return None
    ov = overlap_ratio(q, chunk["text"])
    # >70% verbatim overlap means the question is a keyword restatement of the passage,
    # which would pass on lexical match alone and tell us nothing about the embeddings.
    if ov > 0.70:
        return None
    return {
        "stratum": stratum,
        "prompt": q,
        "gold_source": chunk["source"],
        "gold_page": chunk.get("page"),
        "gold_folder": chunk.get("folder"),
        "gold_chunk_idx": idx,
        "overlap": round(ov, 3),
        "chunk_preview": chunk["text"][:200].replace("\n", " "),
    }


def main():
    with open(CHUNKS_PKL, "rb") as f:
        chunks = pickle.load(f)["chunks"]
    print(f"Loaded {len(chunks)} chunks from {CHUNKS_PKL}")

    pools = pick_pools(chunks)
    for s in STRATA:
        print(f"  pool {s:20s} {len(pools[s]):6d} candidate chunks")

    # oversample by 40% so that questions rejected for high lexical overlap or bad
    # formatting still leave us at the target count
    jobs = []
    for stratum, target in STRATA.items():
        pool = pools[stratum]
        if not pool:
            print(f"  ! no candidates for {stratum}, skipping")
            continue
        want = min(int(target * 1.4), len(pool))
        for idx in random.sample(pool, want):
            jobs.append((idx, chunks[idx], stratum))
    random.shuffle(jobs)
    print(f"\nGenerating {len(jobs)} candidate questions on {GEN_MODEL} "
          f"({WORKERS} workers)...")

    results = []
    with ThreadPoolExecutor(max_workers=WORKERS) as ex:
        for n, out in enumerate(ex.map(gen_one, jobs), 1):
            if out:
                results.append(out)
            if n % 25 == 0:
                print(f"  {n}/{len(jobs)} generated, {len(results)} kept")

    # trim back to the target count per stratum, preferring the LOWEST lexical overlap
    # (those are the questions that most require real semantic matching)
    by_s = defaultdict(list)
    for r in results:
        by_s[r["stratum"]].append(r)
    final = []
    for stratum, target in STRATA.items():
        got = sorted(by_s[stratum], key=lambda r: r["overlap"])[:target]
        final.extend(got)
        print(f"  kept {stratum:20s} {len(got):3d}/{target}")

    random.shuffle(final)
    for i, r in enumerate(final):
        r["id"] = f"h{i:04d}"
    with open(OUT, "w") as f:
        for r in final:
            f.write(json.dumps(r) + "\n")

    avg = sum(r["overlap"] for r in final) / max(len(final), 1)
    print(f"\nWrote {len(final)} hard retrieval prompts -> {OUT}")
    print(f"Mean lexical overlap with gold chunk: {avg:.2f} (lower = more semantic)")


if __name__ == "__main__":
    main()
