#!/usr/bin/env python3
"""Generate the light theme from the dark CSS, deterministically.

The site's default look is the dark green stage. Light mode is not a second
hand-maintained stylesheet - it is DERIVED from the dark one by this script,
which parses the main <style> block of landing/index.html, maps every colour
that only makes sense on a dark ground to its light-ground equivalent, and
writes the result between the LIGHT-THEME markers inside that same <style>
block, every selector scoped under html[data-theme="light"].

Because it is generated, a dark-mode edit can never silently leave light mode
behind: regenerate, or --check fails.

Mapping rules (property-aware):
  colour text     white / white-alpha  -> deep green-grey ink
                  lime / pale greens   -> readable deep green
                  pale blue / amber    -> their dark-ground equivalents
  backgrounds     dark glass + scrims  -> white glass / light scrim
                  faint white glass    -> solid-ish white glass
  borders         white-alpha          -> green-grey hairlines
  shadows         black glows          -> soft grey, text-shadows dropped
Anything already legible on both grounds (site greens, ambers, blues used as
fills, lime-tinted backgrounds) passes through untouched.

Usage:
  python3 scripts/build_light_theme.py           # regenerate in place
  python3 scripts/build_light_theme.py --check   # guard: fail if stale
"""
from __future__ import annotations
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAGE = ROOT / "landing" / "index.html"
START = "/* ==== LIGHT THEME (generated by scripts/build_light_theme.py) ==== */"
END = "/* ==== END LIGHT THEME ==== */"

# ---------------------------------------------------------------- palette maps
INK_TEXT = "#142a1e"            # replaces pure white text
LIME_TEXT = "#177a37"           # replaces lime text
PALE_GREEN_TEXT = "#1c6b34"     # replaces #e4ffb0-family text
BLUE_TEXT = "#12699c"           # replaces #63bfe6
AMBER_TEXT = "#8a5c12"          # replaces #e0b25e / #f0cf98

DARK_HEX_BG = {"#072b1f": "rgba(255,255,255,.85)", "#0c2a1b": "rgba(255,255,255,.85)",
               "#0a2016": "rgba(255,255,255,.85)", "#08301c": "rgba(255,255,255,.85)"}
HEX_TEXT = {
    "#fff": INK_TEXT, "#ffffff": INK_TEXT,
    "#c6ff6a": LIME_TEXT,
    "#e4ffb0": PALE_GREEN_TEXT, "#eeffcf": PALE_GREEN_TEXT,
    "#dff0c8": PALE_GREEN_TEXT, "#cfe6b8": PALE_GREEN_TEXT,
    "#9ed44a": "#4d7c15", "#63bfe6": BLUE_TEXT,
    "#e0b25e": AMBER_TEXT, "#f0cf98": AMBER_TEXT,
}

DARK_GREENS = {(4, 14, 10), (4, 16, 11), (6, 18, 13), (6, 20, 14), (7, 30, 20),
               (7, 43, 31), (9, 26, 19), (9, 40, 27), (11, 46, 32), (12, 52, 35)}
DARK_GLASS = re.compile(
    r"rgba\((?:6,20,14|6,18,13|4,16,11|11,46,32|9,26,19|7,43,31|7,30,20|9,40,27|12,52,35|4,14,10|0,0,0)\s*,\s*[0-9.]+\)")


def _rgba(m):
    r, g, b, a = m.groups()
    return int(r), int(g), int(b), float(a)


RGBA = re.compile(r"rgba\((\d+),\s*(\d+),\s*(\d+)\s*,\s*([0-9.]+)\)")


def map_color_token(tok: str, prop: str) -> str:
    """Map one colour token for the given property context."""
    low = tok.lower()
    if low in ("var(--lime)",):
        if prop.startswith("color"):
            return LIME_TEXT
        return "rgba(36,138,61,.55)"        # lime borders/fills -> green line
    if low in HEX_TEXT and (prop.startswith("color") or prop == "fill"):
        return HEX_TEXT[low]
    if low in ("#fff", "#ffffff") and prop.startswith("border"):
        return "rgba(20,50,35,.35)"
    if low in DARK_HEX_BG and prop.startswith("background"):
        return DARK_HEX_BG[low]
    m = RGBA.fullmatch(tok)
    if not m:
        return tok
    r, g, b, a = _rgba(m)
    if (r, g, b) == (255, 255, 255):
        if prop.startswith("color"):
            return f"rgba(12,32,22,{min(.95, max(.55, a + .15)):.2f})"
        if prop.startswith("border") or prop == "outline":
            return f"rgba(20,50,35,{min(.32, a * .8 + .06):.2f})"
        if prop.startswith("background"):
            # faint dark-glass card -> real light glass
            return "rgba(255,255,255,.66)" if a <= .2 else tok
        return tok
    if (r, g, b) in DARK_GREENS:
        return "rgba(255,255,255,.72)"
    if (r, g, b) == (198, 236, 143) or (r, g, b) == (198, 255, 106):
        if prop.startswith("color"):
            return LIME_TEXT
        if prop.startswith("border"):
            return "rgba(36,138,61,.42)"
        return tok                            # lime-tinted fills read fine
    if (r, g, b) == (0, 0, 0):
        return f"rgba(140,160,150,{a * .5:.2f})"
    return tok


COLOR_TOKEN = re.compile(r"rgba\([^)]*\)|#[0-9a-fA-F]{3,8}|var\(--lime\)")


def map_value(prop: str, value: str) -> str:
    if prop == "text-shadow":
        return "none"
    if prop.startswith("background") and DARK_GLASS.search(value) \
            and "gradient" in value:
        return "linear-gradient(180deg,rgba(238,241,240,.88),rgba(232,238,235,.78))"
    if prop.startswith("background") and value.strip() in ("var(--ink)", "var(--ink-2)"):
        return "var(--bg)"
    return COLOR_TOKEN.sub(lambda m: map_color_token(m.group(0), prop), value)


RELEVANT = ("color", "background", "border", "text-shadow", "outline",
            "box-shadow", "fill", "stroke")


def relevant_prop(prop: str) -> bool:
    return prop.startswith(RELEVANT)


def scope(selector: str) -> str:
    parts = []
    for sel in selector.split(","):
        sel = sel.strip()
        if not sel:
            continue
        if sel in (":root", "html"):
            parts.append('html[data-theme="light"]')
        elif sel.startswith("body"):
            parts.append('html[data-theme="light"] ' + sel)
        else:
            parts.append('html[data-theme="light"] ' + sel)
    return ",\n".join(parts)


def transform_block(css: str) -> list[str]:
    """Walk top-level rules; recurse into @media; skip @keyframes/@font."""
    out = []
    i, n = 0, len(css)
    while i < n:
        b = css.find("{", i)
        if b == -1:
            break
        head = css[i:b].strip()
        # find matching close brace
        depth, j = 1, b + 1
        while j < n and depth:
            if css[j] == "{":
                depth += 1
            elif css[j] == "}":
                depth -= 1
            j += 1
        body = css[b + 1:j - 1]
        i = j
        if head.startswith("@keyframes") or head.startswith("@font"):
            continue
        if head.startswith("@media") or head.startswith("@supports"):
            inner = transform_block(body)
            if inner:
                out.append(head + "{\n" + "\n".join(inner) + "\n}")
            continue
        if head.startswith("@"):
            continue
        decls = []
        for d in body.split(";"):
            if ":" not in d:
                continue
            prop, _, val = d.partition(":")
            prop = prop.strip().lower()
            val = val.strip()
            if not relevant_prop(prop):
                continue
            new = map_value(prop, val)
            if new != val:
                decls.append(f"  {prop}:{new};")
        if decls:
            out.append(scope(head) + "{\n" + "\n".join(decls) + "\n}")
    return out


# Hand-written structural rules the mapping cannot derive: stages, videos,
# scrims, the deck, inline-SVG figure colours (matched by attribute), the
# theme toggle itself.
MANUAL = """
/* -- structure: stages become light ground, footage goes dark-only -- */
html[data-theme="light"]{color-scheme:light;}
html[data-theme="light"] .vstage{background:var(--bg);color:#142a1e;}
html[data-theme="light"] .vstage video,
html[data-theme="light"] .vstage .loop-scrim,
html[data-theme="light"] .md-vid,
html[data-theme="light"] .amb,
html[data-theme="light"] .grain{display:none !important;}
html[data-theme="light"] .md-deck{background:#e8eeeb;color:#142a1e;}
html[data-theme="light"] .md-slide::before,
html[data-theme="light"] .md-slide::after{display:none;}
html[data-theme="light"] .md-panel{
  background:rgba(255,255,255,.78);
  border:1px solid rgba(20,60,40,.14);
  box-shadow:0 18px 50px rgba(120,140,130,.25),inset 0 1px 0 rgba(255,255,255,.8);}
html[data-theme="light"] .md-panel h2,
html[data-theme="light"] .md-panel h3.serif{color:#0f2418;text-shadow:none;}
html[data-theme="light"] .md-nav{background:rgba(255,255,255,.8);color:#142a1e;
  border-color:rgba(20,60,40,.2);}
html[data-theme="light"] .md-dot{background:rgba(20,60,40,.25);}
html[data-theme="light"] .md-dot.on{background:#248A3D;}
/* inline SVG figures: the generator cannot reach presentation attributes */
html[data-theme="light"] .md-art [stroke="#fff"]{stroke:#1d3a2a;}
html[data-theme="light"] .md-art [fill="#fff"]{fill:#1d3a2a;}
html[data-theme="light"] .md-art [stroke="rgba(255,255,255,.42)"],
html[data-theme="light"] .md-art [stroke="rgba(255,255,255,.34)"],
html[data-theme="light"] .md-art [stroke="rgba(255,255,255,.16)"]{stroke:rgba(20,50,35,.45);}
html[data-theme="light"] .md-art [fill="rgba(255,255,255,.55)"]{fill:rgba(15,40,28,.6);}
html[data-theme="light"] .md-art [fill="#C6FF6A"]{fill:#248A3D;}
html[data-theme="light"] .md-art [stroke="#C6FF6A"]{stroke:#248A3D;}
html[data-theme="light"] .md-art [fill="rgba(11,46,32,1)"]{fill:#fff;}
/* the district map draws itself with dark-stage fills */
html[data-theme="light"] #ap-map path{
  fill:rgba(36,138,61,.16) !important;stroke:rgba(20,60,40,.4) !important;}
html[data-theme="light"] #ap-map path:hover{fill:rgba(36,138,61,.32) !important;}
html[data-theme="light"] #ap-map path.selected{fill:rgba(36,138,61,.55) !important;
  stroke:#248A3D !important;}
html[data-theme="light"] #ap-map text{fill:#142a1e !important;}
/* the toggle */
.theme-btn{display:inline-flex;align-items:center;justify-content:center;
  width:38px;height:38px;border-radius:50%;cursor:pointer;
  border:1px solid rgba(255,255,255,.3);background:rgba(255,255,255,.1);
  color:#fff;font-size:17px;}
.theme-btn:hover{border-color:var(--lime);}
.theme-btn .ti-sun{display:none;}
html[data-theme="light"] .theme-btn{border-color:rgba(20,60,40,.3);
  background:rgba(255,255,255,.7);color:#14401f;}
html[data-theme="light"] .theme-btn .ti-sun{display:inline;}
html[data-theme="light"] .theme-btn .ti-moon{display:none;}
"""


def build() -> str:
    s = PAGE.read_text()
    a = s.index("<style>") + len("<style>")
    b = s.index("</style>", a)
    css = s[a:b]
    # never feed our own output back into the generator
    if START in css:
        css = css[:css.index(START)]
    rules = transform_block(css)
    return START + "\n" + MANUAL + "\n" + "\n".join(rules) + "\n" + END


def main() -> int:
    check = "--check" in sys.argv
    s = PAGE.read_text()
    block = build()
    if START in s:
        pre = s[:s.index(START)]
        post = s[s.index(END) + len(END):]
        new = pre + block + post
    else:
        b = s.index("</style>")
        new = s[:b] + block + "\n" + s[b:]
    if check:
        if new != s:
            print("STALE light theme: run scripts/build_light_theme.py")
            return 1
        print("OK: light theme current")
        return 0
    PAGE.write_text(new)
    print(f"Light theme written: {len(block)} chars, {block.count('{')} rules")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
